[windows_2025_dc]
dc01 ansible_host=[direccionIP] ansible_port=[PuertoSSH]

[windows_2025_dc:vars]
ansible_connection=ssh
ansible_user=Administrador
ansible_shell_type=powershell
ansible_shell_executable=powershell.exe
ansible_ssh_pass=[Contraseña]

#NOTA: Se aclara que los valores entre corchetes deben ser reemplazados por la información correspondiente. 
#direccionIP: Dirección IP del servidor Windows 2025 DC.
#PuertoSSH: Puerto SSH configurado en el servidor Windows 2025 DC.
#Contraseña: Contraseña del usuario Administrador para la conexión SSH.

#Además de eso se recomienda que la contraseña este protegida en un vault.yml pero por tiempo de ese ejercicio se dejará directamente en el archivo.