[windows_2025_dc]
# dc01 ansible_host=10.0.0.10 ansible_user=ansible-cis
# dc02 ansible_host=10.0.0.11 ansible_user=ansible-cis

[windows_2025_dc:vars]
ansible_connection=ssh
ansible_port=22
ansible_shell_type=powershell
# Recommended: key-based authentication
# ansible_ssh_private_key_file=~/.ssh/id_ed25519
