[windows_2025_dc]
dc01 ansible_host=172.30.96.1 ansible_port=2200

[windows_2025_dc:vars]
ansible_connection=ssh
ansible_user=Administrador
ansible_shell_type=powershell
ansible_shell_executable=powershell.exe
ansible_ssh_pass=Ingreso10manimanitomanolo2709
