---
- name: Apply CIS User Rights Assignment
  ansible.windows.win_user_right:
    name: "{{ item.name }}"
    users: "{{ item.users }}"
    action: set
  loop: "{{ cis_user_rights }}"
  throttle: 6
  loop_control:
    label: "{{ item.id }} - {{ item.name }}"
